services:
  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${PM_PUBLIC_PORT}:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:12.4.0-19913286788
    env_file:
      - ./.env
    container_name: ${GRAFANA_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${GF_PUBLIC_PORT}:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    depends_on:
      - prometheus
volumes:
  grafana-data: